unstable_features = true

comment_width = 90
fn_args_density = "Compressed"
fn_single_line = true
indent_style = "Visual"
imports_layout = "HorizontalVertical"
merge_imports = true
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true