extern crate serde_json;

use graphics::{AtlasError, ImageError};
use std::io::ErrorKind as IOError;
use serde_json::error::Category as SerdeError;
use sound::SoundError;

#[derive(Clone, Debug)]
/// An error generated by some Quicksilver subsystem
pub enum QuicksilverError {
    /// An error from an image atlas
    AtlasError(AtlasError),
    /// An error from loading an image
    ImageError(ImageError),
    /// An error from loading a sound
    SoundError(SoundError),
    /// An error from loading a file
    IOError(IOError),
    /// A serialize or deserialize error
    SerdeError(SerdeError)
}

impl From<ImageError> for QuicksilverError {
    fn from(err: ImageError) -> QuicksilverError {
        QuicksilverError::ImageError(err)
    }
}

impl From<SoundError> for QuicksilverError {
    fn from(err: SoundError) -> QuicksilverError {
        QuicksilverError::SoundError(err)
    }
}

impl From<AtlasError> for QuicksilverError {
    fn from(err: AtlasError) -> QuicksilverError {
        QuicksilverError::AtlasError(err)
    }
}

impl From<IOError> for QuicksilverError {
    fn from(err: IOError) -> QuicksilverError {
        QuicksilverError::IOError(err)
    }
}

impl From<serde_json::Error> for QuicksilverError {
    fn from(err: serde_json::Error) -> QuicksilverError {
        QuicksilverError::SerdeError(err.classify())
    }
}
